# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Filter-HTTPHeadersFixup
version:      0.04
version_from: lib/Apache/Filter/HTTPHeadersFixup.pm
installdirs:  site
requires:
    Apache::Test:                  1.10
    mod_perl:                      1.9915

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
