# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Filter-HTTPHeadersFixup
version:      0.01
version_from: lib/Apache/Filter/HTTPHeadersFixup.pm
installdirs:  site
requires:
    mod_perl:                      1.9911

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
